[2023-12-05 22:07:23,773] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:23] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:35,788] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:35] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:35,791] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:35] "POST /predicao HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:36,106] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:36] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:36,124] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:36] "GET /acidentes_riscos?dia=5&mes=11&id_trecho=2&id_sentido=3 HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:36,420] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:36] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:36,729] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:36] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:36,997] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:36] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:37,034] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:37] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:37,308] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:37] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:37,338] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:37] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:49,495] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:49] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:49,496] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:49] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:49,804] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:49] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:50,073] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:50] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:50,121] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:50] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:50,384] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:50] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:50,431] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:50] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:50,697] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:50] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:57,361] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:57] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:57,361] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:57] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:57,362] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:57] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:57,362] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:57] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:57,392] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:57] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:07:57,674] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:07:57] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:08:10,501] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:08:10] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:08:10,501] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:08:10] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:08:10,501] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:08:10] "GET /riscos HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:08:27,991] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:08:27,992] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:08:27] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:08:40,214] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:08:40,214] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:08:40] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:08:40,480] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
[2023-12-05 22:08:40,481] INFO _log() L96   127.0.0.1 - - [05/Dec/2023 22:08:40] "[35m[1mGET /riscos HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\venv\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-05 22:08:40,821] WARNING get_riscos() L150  Erro ao consultar os riscos com erro QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r), Não foi possível consultar os riscos:/QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r) - call_trace=C:\mvp\puc-rio-mvp-sprint-04-sistemas-inteligentes\projeto\API\app.py L150 
